### PR TITLE
Add sudo

### PR DESCRIPTION
**Pull request by CHBMB**
Then can run ```sudo -u abc beet import /folder``` and it will maintain file permissions as defined in UID

### CODE REVIEW

**Comment by tobbenb** [comment]
You could also do this:
'docker exec -it -u abc beets beet import'

Then the command is run as user abc inside the container.

**Comment by sparklyballs** [comment]
retest this please

**Comment by sparklyballs** [comment]
retest this please

**Comment by sparklyballs** [comment]
retest this please

**Comment by sparklyballs** [comment]
retest this please

**Comment by sparklyballs** [comment]
retest this please

**Comment by sparklyballs** [comment]
retest this please

**Pull request closed without merging**
