### PR TITLE
Adding badfiles plugin default checkers

### PR DESCRIPTION
**Pull request by jsetton**
Adding the default checkers (flac & mp3val) for the [bad files plugin](https://beets.readthedocs.io/en/v1.4.7/plugins/badfiles.html#configuring)

### CODE REVIEW

**Comment by jsetton** [comment]
Can anyone review this PR? Thanks.

**Comment by CHBMB** [comment]
@jsetton Can you perhaps elaborate on what it adds.

Not all of us use beets.

**Comment by jsetton** [comment]
@CHBMB These are the default binaries used by the bad files plugin to identify corrupted or invalid formatted files part of a beet library. As per the documentation below, the `mp3val` binary is used to check MP3 formatted file and `flac` for flac files.

https://beets.readthedocs.io/en/v1.4.7/plugins/badfiles.html

**Comment by thelamer** [comment]
Yeah I'm game, you need to apply the same changes to the armhf and aarch64 docker files. You can build them locally on an x86 machine like this to test: 
```
docker run --rm --privileged multiarch/qemu-user-static:register --reset
docker build -f Dockerfile.aarch64 -t testarm64 .
docker build -f Dockerfile.armhf -t testarm .
```
Also the readme changes need to be made the vars file not directly to the readme, we template our readmes due to the number of repos we maintain. 
https://github.com/linuxserver/docker-beets/blob/master/readme-vars.yml#L42

**Comment by jsetton** [comment]
@thelamer thanks for the details. I made the changes you recommended and was able to build successfully the armhf and aarch64 docker files locally.

**Pull request merged**
